name: Portfolio_Actions_CI

on:

  push:
    branches: [ "master" ]



jobs:
 
  build:
   
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: clean
        run: npm run clean

      - name: build
        run: npm run build 

      - name: clean
        run: npm run deploy 

      - name: Run a one-line script
        run: echo run my custom Workflow successfully!


